# Generated by Django 4.2 on 2023-04-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=50)),
                ('p_desc', models.TextField()),
                ('p_github', models.CharField(max_length=50)),
                ('p_img', models.ImageField(upload_to='images')),
                ('p_website', models.CharField(max_length=50)),
            ],
        ),
    ]
