# Generated by Django 4.2 on 2023-04-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_icon', models.CharField(max_length=50)),
                ('ser_title', models.CharField(max_length=50)),
                ('ser_desc', models.TextField()),
            ],
        ),
    ]
