# Generated by Django 4.2 on 2023-04-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='long_desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_desc',
            field=models.TextField(default=''),
        ),
    ]
