# Generated by Django 4.2 on 2023-04-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_key', models.CharField(max_length=50)),
                ('about_value', models.CharField(max_length=50)),
            ],
        ),
    ]
