# Generated by Django 4.2 on 2023-04-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyStaticInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_off_no', models.CharField(max_length=50)),
                ('my_off_email', models.CharField(max_length=50)),
                ('my_off_address', models.CharField(max_length=50)),
                ('my_cv', models.FileField(default=None, max_length=300, null=True, upload_to='CV/')),
            ],
        ),
    ]
